apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ugcpnmme0-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ugcpnmme0-java-springboot-gitops